# Problem 2 - Even Fibonacci Numbers
#
# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:
#		1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms.

num1 = 1
num2 = 2
num3 = 0
total = 0
print("1\n2")

while True:
	num3 = num1 + num2
	if num3 > 4000000:
		break
	print(num3)
	if num3 % 2 == 0:
		total += num3
	num1 = num2
	num2 = num3

print("sum: " + str(total) + " +2 = " + str(total + 2))
