# Problem 2 - Even Fibonacci Numbers
#
# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:
#		1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms.

from timer import timed


@timed
def problem_002() -> int:
    limit = 4000000
    a, b, c = 1, 1, 1
    total = 0
    while True:
        c = a + b
        a = b
        b = c
        if c > limit:
            break
        if c % 2 == 0:
            total += c
    return total


if __name__ == '__main__':
    print(f"answer: {problem_002()}")
